# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Charrlotte Adelina Personal Website
email: c.adelina@fu-berlin.de
description: > # this means to ignore newlines until "baseurl:"
  Researcher at FU Berlin
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.charrlotteadelina.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username: ""

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include
include: ["_pages"]

# Collections
collections:
  works:
    output: true
    permalink: /works/:name/
    directory: _works
  peerreview:
    output: true
    permalink: /peerreview/:name/
    directory: _peerreview
  bookreview:
    output: true
    permalink: /bookreview/:name/
    directory: _bookreview
  policyreports:
    output: true
    permalink: /policyreports/:name/
    directory: _policyreports
  clients:
    output: false
  workpics:
    output: true
    permalink: /_workpics
  currents:
    output: true
    permalink: /:collection/:name

# Defaults
defaults:
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "works"
    values:
      layout: "default"
      home: false
      priority: "a"
  -
    scope:
      path: ""
      type: "clients"
    values:
      priority: "a"
  -
    scope:
      path: ""
      type: "workpics"
    values:
      layout: "default"
      home: false
      priority: "a"
  -
    scope:
      path: ""
      type: "currents"
    values:
      layout: "default"

# Plug-ins
plugins:
  - jekyll-paginate-v2